//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressManager.WASalesTax {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WASalesTax.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLocCode", ReplyAction="*")]
        AddressManager.WASalesTax.GetLocCodeResponse GetLocCode(AddressManager.WASalesTax.GetLocCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLocCode", ReplyAction="*")]
        System.Threading.Tasks.Task<AddressManager.WASalesTax.GetLocCodeResponse> GetLocCodeAsync(AddressManager.WASalesTax.GetLocCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLocCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLocCode", Namespace="http://tempuri.org/", Order=0)]
        public AddressManager.WASalesTax.GetLocCodeRequestBody Body;
        
        public GetLocCodeRequest() {
        }
        
        public GetLocCodeRequest(AddressManager.WASalesTax.GetLocCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLocCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string street;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string zip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string loccode;
        
        public GetLocCodeRequestBody() {
        }
        
        public GetLocCodeRequestBody(string street, string city, string zip, string loccode) {
            this.street = street;
            this.city = city;
            this.zip = zip;
            this.loccode = loccode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLocCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLocCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public AddressManager.WASalesTax.GetLocCodeResponseBody Body;
        
        public GetLocCodeResponse() {
        }
        
        public GetLocCodeResponse(AddressManager.WASalesTax.GetLocCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLocCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetLocCodeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loccode;
        
        public GetLocCodeResponseBody() {
        }
        
        public GetLocCodeResponseBody(int GetLocCodeResult, string loccode) {
            this.GetLocCodeResult = GetLocCodeResult;
            this.loccode = loccode;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : AddressManager.WASalesTax.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<AddressManager.WASalesTax.ServiceSoap>, AddressManager.WASalesTax.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddressManager.WASalesTax.GetLocCodeResponse AddressManager.WASalesTax.ServiceSoap.GetLocCode(AddressManager.WASalesTax.GetLocCodeRequest request) {
            return base.Channel.GetLocCode(request);
        }
        
        public int GetLocCode(string street, string city, string zip, ref string loccode) {
            AddressManager.WASalesTax.GetLocCodeRequest inValue = new AddressManager.WASalesTax.GetLocCodeRequest();
            inValue.Body = new AddressManager.WASalesTax.GetLocCodeRequestBody();
            inValue.Body.street = street;
            inValue.Body.city = city;
            inValue.Body.zip = zip;
            inValue.Body.loccode = loccode;
            AddressManager.WASalesTax.GetLocCodeResponse retVal = ((AddressManager.WASalesTax.ServiceSoap)(this)).GetLocCode(inValue);
            loccode = retVal.Body.loccode;
            return retVal.Body.GetLocCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AddressManager.WASalesTax.GetLocCodeResponse> AddressManager.WASalesTax.ServiceSoap.GetLocCodeAsync(AddressManager.WASalesTax.GetLocCodeRequest request) {
            return base.Channel.GetLocCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<AddressManager.WASalesTax.GetLocCodeResponse> GetLocCodeAsync(string street, string city, string zip, string loccode) {
            AddressManager.WASalesTax.GetLocCodeRequest inValue = new AddressManager.WASalesTax.GetLocCodeRequest();
            inValue.Body = new AddressManager.WASalesTax.GetLocCodeRequestBody();
            inValue.Body.street = street;
            inValue.Body.city = city;
            inValue.Body.zip = zip;
            inValue.Body.loccode = loccode;
            return ((AddressManager.WASalesTax.ServiceSoap)(this)).GetLocCodeAsync(inValue);
        }
    }
}
